### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by its-thabani** [nyuszika7h/noinappsafari#6]
How do I get this working on a normal iphone 14?

**Comment by ghost** [comment]
You don't, there is no jailbreak available for iPhone 14 yet.

**Comment by its-thabani** [comment]
I found a way to temporarily jailbreak my iphone 14. but I can't install the app from any repo...do you have any guidance of what to do after jailbreak e.g. which package manager to install, and how to access the repo (last time I tried accessing the repo from Cydia or Sileo but it didn't work or it would say repo url is wrong format

**Comment by ghost** [comment]
Whatever you found is a fake jailbreak.

**Comment by its-thabani** [comment]
this one (https://pangu8.com/jailbreak/iphone-14/), I'm sure it works because other jailbreak tweaks work right after

**Comment by its-thabani** [comment]
what about for my old iphone 11pro, it's jailbroken but I don't know how to install the tweak (what's the repo url)

**Comment by ghost** [comment]
> this one (https://pangu8.com/jailbreak/iphone-14/), I'm sure it works because other jailbreak tweaks work right after

That's impossible. The most you may be able to use is MacDirtyCow (MDC) tweaks if you're on iOS 16.0–16.1.2, but that's not a full jailbreak and you can't install regular tweaks, it's more limited and they have to be made specifically for it. I don't think this tweak can be ported to MDC.

> what about for my old iphone 11pro, it's jailbroken but I don't know how to install the tweak (what's the repo url)

https://repo.alexia.lol

**Comment by its-thabani** [comment]
there's also this which seems to have a good reviews (https://www.youtube.com/watch?v=Esl89a_Sr4M)

**Comment by ghost** [comment]
That only works on iPhone X and below, it relies on a hardware vulnerability that was patched on newer devices.

**Comment by its-thabani** [comment]
Okay, thanks
